server:
  port: ${PORT:8080}

spring:
  application:
    name: mysoftpos-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000        # 5 min
      connection-timeout: 10000   # 10 sec
      max-lifetime: 1800000       # 30 min
  jpa:
    open-in-view: false
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.MySQLDialect}

app:
  jwt:
    secret: ${APP_JWT_SECRET}
    access-token-expiration: 3600000    # 1 hour
    refresh-token-expiration: 604800000 # 7 days

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
